rvm:
  - 1.9.3
  - 2.0.0
  - 2.2.1
notifications:
  # overriding this so billing@teamsporttech.com (who owns the repo) doesn't get spammed
  # anyone, feel free to add yourselves
  email:
    - patrick.byrne@tstmedia.com
    - jon.karna@tstmedia.com
